'use client'
import { useEffect, useState } from 'react'
import AdminLayout from '../components/AdminLayout'
const API=process.env.NEXT_PUBLIC_API_URL
export default function Page(){
  const [data,setData]=useState([])
  const [form,setForm]=useState({judul:'',tipe_properti:'Rumah',tipe_transaksi:'jual',harga_cash:0,harga_kredit:'',dp:'',cicilan_per_bulan:'',tenor_bulan:'',harga_sewa_per:'bulan',alamat:'',kecamatan:'',luas_tanah:0,luas_bangunan:0,kamar_tidur:2,kamar_mandi:1,sertifikat:'SHM',thumbnail:'',foto_1:'',deskripsi:'',fasilitas:'',wa_number:'',badge:'',is_published:false})
  const [editId,setEditId]=useState(null)
  const tok=()=>document.cookie.split('admin_token=')[1]?.split(';')[0]
  const load=async()=>{const r=await fetch(`${API}/properties`,{headers:{Authorization:`Bearer ${tok()}`}});const j=await r.json();setData(Array.isArray(j)?j:j.data||[])}
  useEffect(()=>{load()},[])
  const submit=async(e)=>{e.preventDefault();const url=editId?`${API}/properties/${editId}`:`${API}/properties`;await fetch(url,{method:editId?'PUT':'POST',headers:{Authorization:`Bearer ${tok()}`, 'Content-Type':'application/json'},body:JSON.stringify(form)});load();setEditId(null)}
  return(<AdminLayout title={`PROPERTI (${data.length})`}><div className="grid lg:grid-cols-[420px_1fr] gap-6 mt-4"><form onSubmit={submit} className="bg-[#16161E] border border-white/10 p-5 rounded-[24px] space-y-2 h-fit max-h-[90vh] overflow-y-auto">
  <input value={form.judul} onChange={e=>setForm({...form,judul:e.target.value})} placeholder="Judul Properti" className="w-full bg-black/50 border border-white/10 p-3 rounded-xl text-sm" required/>
  <div className="grid grid-cols-3 gap-2"><select value={form.tipe_properti} onChange={e=>setForm({...form,tipe_properti:e.target.value})} className="bg-black/50 border border-white/10 p-3 rounded-xl text-sm"><option>Rumah</option><option>Rumah Gadang</option><option>Tanah</option><option>Ruko</option></select><select value={form.tipe_transaksi} onChange={e=>setForm({...form,tipe_transaksi:e.target.value})} className="bg-black/50 border border-white/10 p-3 rounded-xl text-sm"><option value="jual">Jual</option><option value="sewa">Sewa</option><option value="kredit">Kredit</option></select><select value={form.sertifikat} onChange={e=>setForm({...form,sertifikat:e.target.value})} className="bg-black/50 border border-white/10 p-3 rounded-xl text-sm"><option>SHM</option><option>HGB</option><option>SHGB</option></select></div>
  <input type="number" value={form.harga_cash} onChange={e=>setForm({...form,harga_cash:parseInt(e.target.value)||0})} placeholder="Harga Cash" className="w-full bg-black/50 border border-white/10 p-3 rounded-xl text-sm"/>
  <div className="grid grid-cols-2 gap-2"><input type="number" value={form.dp} onChange={e=>setForm({...form,dp:e.target.value?parseInt(e.target.value):null})} placeholder="DP (kredit)" className="bg-black/50 border border-white/10 p-2 rounded-xl text-sm"/><input type="number" value={form.cicilan_per_bulan} onChange={e=>setForm({...form,cicilan_per_bulan:e.target.value?parseInt(e.target.value):null})} placeholder="Cicilan/bulan" className="bg-black/50 border border-white/10 p-2 rounded-xl text-sm"/></div>
  <div className="grid grid-cols-4 gap-2"><input type="number" value={form.luas_tanah} onChange={e=>setForm({...form,luas_tanah:parseInt(e.target.value)||0})} placeholder="LT" className="bg-black/50 border border-white/10 p-2 rounded-xl text-sm"/><input type="number" value={form.luas_bangunan} onChange={e=>setForm({...form,luas_bangunan:parseInt(e.target.value)||0})} placeholder="LB" className="bg-black/50 border border-white/10 p-2 rounded-xl text-sm"/><input type="number" value={form.kamar_tidur} onChange={e=>setForm({...form,kamar_tidur:parseInt(e.target.value)||0})} placeholder="KT" className="bg-black/50 border border-white/10 p-2 rounded-xl text-sm"/><input type="number" value={form.kamar_mandi} onChange={e=>setForm({...form,kamar_mandi:parseInt(e.target.value)||0})} placeholder="KM" className="bg-black/50 border border-white/10 p-2 rounded-xl text-sm"/></div>
  <input value={form.alamat} onChange={e=>setForm({...form,alamat:e.target.value})} placeholder="Alamat" className="w-full bg-black/50 border border-white/10 p-3 rounded-xl text-sm"/><div className="grid grid-cols-2 gap-2"><input value={form.kecamatan} onChange={e=>setForm({...form,kecamatan:e.target.value})} placeholder="Kecamatan" className="bg-black/50 border border-white/10 p-3 rounded-xl text-sm"/><input value={form.wa_number} onChange={e=>setForm({...form,wa_number:e.target.value})} placeholder="WA Number" className="bg-black/50 border border-white/10 p-3 rounded-xl text-sm"/></div>
  <input value={form.thumbnail} onChange={e=>setForm({...form,thumbnail:e.target.value})} placeholder="Thumbnail URL" className="w-full bg-black/50 border border-white/10 p-3 rounded-xl text-sm"/><input value={form.foto_1} onChange={e=>setForm({...form,foto_1:e.target.value})} placeholder="Foto 1 URL" className="w-full bg-black/50 border border-white/10 p-3 rounded-xl text-sm"/><textarea value={form.deskripsi} onChange={e=>setForm({...form,deskripsi:e.target.value})} placeholder="Deskripsi" className="w-full bg-black/50 border border-white/10 p-3 rounded-xl text-sm h-20"/><textarea value={form.fasilitas} onChange={e=>setForm({...form,fasilitas:e.target.value})} placeholder="Fasilitas (koma pisah)" className="w-full bg-black/50 border border-white/10 p-3 rounded-xl text-sm h-16"/><div className="flex items-center gap-2"><input type="checkbox" checked={form.is_published} onChange={e=>setForm({...form,is_published:e.target.checked})}/><span className="text-xs">Publish</span></div>
  <button className="w-full bg-[#D4AF37] text-black py-3 rounded-xl font-black text-xs">{editId?'UPDATE':'SIMPAN'}</button>{editId&&<button type="button" onClick={()=>setEditId(null)} className="w-full bg-white/10 py-3 rounded-xl font-black text-xs">BATAL</button>}
  </form><div className="bg-[#16161E] border border-white/10 p-5 rounded-[24px] space-y-2 max-h-[90vh] overflow-y-auto">{data.map(i=><div key={i.id} className="bg-black/40 border border-white/5 p-3 rounded-xl flex justify-between"><div><p className="text-sm font-bold">{i.judul}</p><p className="text-[11px] text-zinc-500">{i.tipe_properti} - Rp{i.harga_cash} | {i.kecamatan} | {i.is_published?'Published':'Draft'}</p></div><div className="flex gap-1"><button onClick={()=>{setForm(i);setEditId(i.id)}} className="bg-white/10 px-3 py-1 rounded-full text-[10px]">EDIT</button><button onClick={async()=>{if(!confirm('hapus?'))return;await fetch(`${API}/properties/${i.id}`,{method:'DELETE',headers:{Authorization:`Bearer ${tok()}`}});load()}} className="bg-red-500/20 text-red-400 px-3 py-1 rounded-full text-[10px]">HAPUS</button></div></div>)}</div></div></AdminLayout>)
  }
